### ISSUE TITLE
Could we configure this to choose to open NA lodestone links rather than EU lodestone links?

### ISSUE THREAD

**Issue by CharlieDelune** [Infiziert90/Eventy#2]
Would be nice to either read from what region we're connected to, or maybe just make it a dropdown in the settings. It's not a super huge deal but timezones are hard. Let's get rid of timezones.

**Comment by Infiziert90** [comment]
You can already see the exact time frame in the plugin itself, it is auto converted to your timezone that the pc is running on :)

It should show hours when you hover the line, if not, then I simply forgot it and it will be added in the next update

**Comment by CharlieDelune** [comment]
Oh huh, it sure does. I guess that's good enough then!
